# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PodcastApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PodcastApp

  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'PodcastApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PodcastAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end